name: Deploy LiveCodeProject

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: .  # Adjust if your site is in a subfolder like 'dist' or 'public'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
